# version 3
version: "3"

services:

 db:
  env_file: './environment.env'
  image: monitoringartist/zabbix-db-mariadb
  volumes:
   - /etc/localtime:/etc/localtime:ro
  
 zabbix-proxy:
  env_file: './environment.env'
  image: monitoringartist/zabbix-xxl:latest
  hostname: zabbix-proxy-sp
  privileged: true
  ports:
   - 10051:10051
  volumes: 
   - /etc/localtime:/etc/localtime:ro
  links:
   - db 
 
 zabbix-agent:
  image: monitoringartist/dockbix-agent-xxl-limited:latest
  privileged: true
  ports:
   - 10050:10050
  volumes:
   - /:/rootfs
   - /var/run:/var/run
   - /etc/localtime:/etc/localtime:ro
  hostname: zabbix-proxy-sp
  links:
   - zabbix-proxy
