# version 3
version: "3"

services:

 db:
  env_file: './environment.env'
  image: monitoringartist/zabbix-db-mariadb
  volumes:
   - /etc/localtime:/etc/localtime:ro
  
 zabbix-proxy:
  env_file: './environment.env'
  image: monitoringartist/zabbix-xxl:latest
  hostname: zabbix-proxy-sp
  privileged: true
  ports:
   - 10051:10051
  volumes: 
   - /etc/localtime:/etc/localtime:ro
  links:
   - db 
